language: node_js
node_js:
   - "7"
branches:
   only:
      - master
script:
   - cd frontend
   - npm install
   - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: master