export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
export const DELETE_POST = 'DELETE_POST';
export const EDIT_POST = 'EDIT_POST';
export const REQUEST_POSTS = 'REQUEST_POSTS';

export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';

export const UPDATE_POST_VOTESCORE = 'UPDATE_POST_VOTESCORE';
export const UPDATE_COMMENT_VOTESCORE = 'UPDATE_COMMENT_VOTESCORE';
export const DELETE_COMMENT = 'DELETE_COMMENT';
